site_name: FWI2025 Equations
repo_url: "https://github.com/nrcan-cfs-fire/cffdrs-ng"
theme:
  name: shadcn
  icon: mynaui:tree
  custom_dir: custom_theme/
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
